name: Dependabot Merger

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-22.04
    if: github.actor == 'dependabot[bot]'
    timeout-minutes: 1
    permissions:
      contents: write
      pull-requests: write
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: dependabot/fetch-metadata@v1.3.5
        id: meta

      - name: Approve and Merge
        if: |
          (steps.meta.outputs.package-ecosystem == 'github_actions') ||
          (steps.meta.outputs.package-ecosystem == 'pip')
        run: |
          gh pr checkout "${PR_URL}"
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ]; then
            gh pr review --approve "${PR_URL}"
          else
            echo "pull-request already approved"
          fi
          gh pr merge --auto --squash "${PR_URL}"
